import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  // Open Graph (Untuk semua platform)
  openGraph: {
    title: 'FinnyAIBot - Solusi Pencatatan Keuangan UMKM',
    description: 'Bantu UMKM kelola keuangan lebih mudah dengan bot pencatatan otomatis, upload struk, dan laporan Excel.',
    url: 'https://finny-ai.my.id',
    siteName: 'FinnyAIBot',
    images: [
      {
        url: 'https://finny-ai.my.id/images/Logo.png', // Ganti dengan URL gambar Anda
        width: 1200,
        height: 630,
        alt: 'Ilustrasi FinnyAIBot',
      },
    ],
    locale: 'id_ID',
    type: 'website',
  },
  
  // Twitter Cards (Khusus untuk Twitter/X)
  twitter: {
    card: 'summary_large_image',
    title: 'FinnyAIBot - Solusi Pencatatan Keuangan UMKM',
    description: 'Bantu UMKM kelola keuangan lebih mudah dengan bot pencatatan otomatis, upload struk, dan laporan Excel.',
    images: ['https://finny-ai.my.id/images/Logo.png'], // Ganti dengan URL gambar Anda
  },
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
